//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBERJOBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDOS_REALIZADOS
    {
        public int ID { get; set; }
        public string CLIENTE { get; set; }
        public string PLATOS { get; set; }
        public System.DateTime FECHA { get; set; }
        public string DIRECCION_DE_ENTREGA { get; set; }
        public string TRABAJADOR { get; set; }
        public decimal PRECIO { get; set; }
        public decimal TOTAL { get; set; }
        public Nullable<int> ID_REF { get; set; }
    }
}
